export const REQ='REQ';
export const SLAMBOOK_FAILURE='SLAMBOOK_FAILURE'
export const STATE_CLEANUP='STATE_CLEANUP'
export const GET_SLAMBOOK_BY_USER_ID_RECEIVED='GET_SLAMBOOK_BY_USER_ID_RECEIVED'
export const GET_SLAMBOOK_BY_USER_ID_SENT='GET_SLAMBOOK_BY_USER_ID_SENT'